Server:
  port: 8080
  host: localhost
GrpcServer:
  Port: ":9090"
Database:
  driver: postgres
  host: localhost
  port: 5432
  name: authDatabase
  user: postgres
  password: postgres
  sslMode: disable
Kafka:
  Brokers:
    - 127.0.0.1:19092
  Producer:
    topic: "user-verification"
  Consumer:
    topics:
      - "user-verification"

