Server:
  port: 8082
  host: localhost
Database:
  driver: postgres
  host: localhost
  port: 5432
  name: galleryService
  user: postgres
  password: postgres
  sslMode: disable
Transport:
  User:
    host: http://localhost:8080
    Timeout: 5s
  UserGrpc:
    Host: localhost:9090
  AuthService:
    host: http://localhost:8081
    Timeout: 5s
  AuthGrpc:
    Host: localhost:9091