Auth:
  secretKey: secretKey
Server:
  port: 8081
  host: localhost
GrpcServer:
  Port: ":9091"
Database:
  driver: postgres
  host: localhost
  port: 5432
  name: authDatabase
  user: postgres
  password: postgres
  sslMode: disable
Transport:
  User:
    host: http://localhost:8080
    Timeout: 5s
  UserGrpc:
    Host: localhost:9090
